#! /bin/bash

if [ "$1" = "upgrade" ]; then
    echo "updating..."
    docker pull colorfulboard/bq_profile:latest --quiet > /dev/null
    echo "done"
elif [ "$1" = "local" ]; then
    docker run -it --rm -v ~/.config/gcloud:/root/.config/gcloud -v $(pwd):/usr/src/app colorfulboard/bq_profile:latest "${@:2:($#-1)}"
else
    docker run -it --rm -v $(pwd):/usr/src/app colorfulboard/bq_profile:latest "$@"
fi
