#! /bin/bash

case "$1" in
upgrade)
  echo "upgrading..."
  exec docker pull colorfulboard/bq_profile:latest --quiet >/dev/null
  echo "done"
  ;;
local)
  exec docker run -it --rm -v ~/.config/gcloud:/root/.config/gcloud -v $(pwd):/usr/src/app colorfulboard/bq_profile:latest "${@:2:($# - 1)}"
  ;;
*)
  exec docker run -it --rm -v $(pwd):/usr/src/app colorfulboard/bq_profile:latest "$@"
  ;;
esac
